[build]
  base = "app"
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[plugins]]
  package = "netlify-plugin-csp-generator"
  [plugins.inputs]
    buildDir = "dist"
  [plugins.inputs.policies]
    defaultSrc = "'self'"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; img-src 'self' data: https://*.googleapis.com https://*.gstatic.com; script-src 'self' 'unsafe-inline' https://*.googleapis.com https://*.gstatic.com; script-src-elem 'self' 'unsafe-inline' https://*.googleapis.com https://*.gstatic.com; font-src 'self' data: https://fonts.gstatic.com; connect-src 'self' data: ws://localhost:*/ws https://*.googleapis.com https://*.execute-api.us-east-1.amazonaws.com/;"
